kumuluzee:
  name: order-service
  env:
    name: dev
  version: 1.0.0
  discovery:
    etcd:
      hosts: http://localhost:2379
    ttl: 20
    ping-interval: 15
  datasources:
    - jndi-name: jdbc/BooksDS
      connection-url: jdbc:postgresql://postgres:5432/postgres
      username: dbuser
      password: postgres
      max-pool-size: 20
  fault-tolerance:
    config:
      watch-enabled: true
      watch-properties: timeout.value,circuit-breaker.failure-ratio,bulkhead.value
    rabbit:
      bulkhead:
        value: 5
      queue-order:
        timeout:
          value: 1ms
        circuit-breaker:
          request-threshold: 10
          failure-ratio: 0.3
          delay: 3000ms
          metrics:
            rolling-window:
              size: 5s
              buckets: 5
orders:
  rabbit-mq-uri: amqps://admin:admin@portal-ssl676-94.bmix-eu-gb-yp-76826436-8167-446f-8f80-b63de37b51aa.3782795196.composedb.com:16865/bmix-eu-gb-yp-76826436-8167-446f-8f80-b63de37b51aa